name: clothifys_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.1
  google_maps_flutter: ^2.0.8
  cloud_firestore: ^2.5.2
  cloud_firestore_web: ^2.4.2
  firebase_storage: ^10.0.3
  provider: ^6.0.0
  flutter_spinkit: ^5.1.0
  transparent_image: ^2.0.0
  font_awesome_flutter: ^9.1.0
  firebase_core: ^1.6.0
  carousel_pro: ^1.0.0
  image:
  intl:
  uuid:
  http:
  path_provider: ^2.0.3
  flutter_staggered_grid_view: ^0.4.0
  image_picker: ^0.8.4
  url_launcher: ^6.0.10
  cupertino_icons: ^1.0.3
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.7
  firebase_auth: ^3.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/logo1.png
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png
    - images/
    - images/5A.jpg



